In [9]:
import pandas as pd
import numpy as np

test_path = 'horseColicTest.txt'
train_path = 'horseColicTraining.txt'

test_data = pd.read_table(test_path, header=None)
train_data = pd.read_table(train_path, header=None)

train_data

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,2.0,1.0,38.5,66.0,28.0,3.0,3.0,0.0,2.0,5.0,...,0.0,0.0,0.0,3.0,5.0,45.0,8.4,0.0,0.0,0.0
1,1.0,1.0,39.2,88.0,20.0,0.0,0.0,4.0,1.0,3.0,...,0.0,0.0,0.0,4.0,2.0,50.0,85.0,2.0,2.0,0.0
2,2.0,1.0,38.3,40.0,24.0,1.0,1.0,3.0,1.0,3.0,...,0.0,0.0,0.0,1.0,1.0,33.0,6.7,0.0,0.0,1.0
3,1.0,9.0,39.1,164.0,84.0,4.0,1.0,6.0,2.0,2.0,...,1.0,2.0,5.0,3.0,0.0,48.0,7.2,3.0,5.3,0.0
4,2.0,1.0,37.3,104.0,35.0,0.0,0.0,6.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,74.0,7.4,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,1.0,1.0,0.0,120.0,70.0,4.0,0.0,4.0,2.0,2.0,...,0.0,0.0,0.0,0.0,5.0,55.0,65.0,0.0,0.0,0.0
295,2.0,1.0,37.2,72.0,24.0,3.0,2.0,4.0,2.0,4.0,...,3.0,1.0,0.0,4.0,4.0,44.0,0.0,3.0,3.3,0.0
296,1.0,1.0,37.5,72.0,30.0,4.0,3.0,4.0,1.0,4.0,...,2.0,1.0,0.0,3.0,5.0,60.0,6.8,0.0,0.0,0.0
297,1.0,1.0,36.5,100.0,24.0,3.0,3.0,3.0,1.0,3.0,...,3.0,1.0,0.0,4.0,4.0,50.0,6.0,3.0,3.4,1.0
298,1.0,1.0,37.2,40.0,20.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,4.0,1.0,36.0,62.0,1.0,1.0,0.0

In [12]:
testX = test_data.iloc[:, :-1].values
testY = test_data.iloc[:, -1].values
trainX = train_data.iloc[:, :-1].values
trainY = train_data.iloc[:, -1].values

testX

array([[ 2. ,  1. , 38.5, ...,  6.3,  0. ,  0. ],
       [ 2. ,  1. , 37.6, ...,  6.3,  1. ,  5. ],
       [ 1. ,  1. , 37.7, ..., 70. ,  3. ,  2. ],
       ...,
       [ 1. ,  1. , 38. , ..., 65. ,  3. ,  2. ],
       [ 2. ,  1. , 38. , ...,  5.8,  0. ,  0. ],
       [ 2. ,  1. , 37.6, ...,  6. ,  0. ,  0. ]])

In [15]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(max_iter=500)
clf.fit(trainX, trainY)
pred = clf.predict(testX)

pred

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1.,
       0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1.,
       0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
       1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.])

In [17]:
from sklearn.metrics import classification_report

t = classification_report(testY, pred, target_names=['0', '1'])
print(t)

              precision    recall  f1-score   support

           0       0.52      0.60      0.56        20
           1       0.82      0.77      0.79        47

    accuracy                           0.72        67
   macro avg       0.67      0.68      0.67        67
weighted avg       0.73      0.72      0.72        67